[package]
authors = ["Meteor <bobogei81123@gmail.com>"]
name = "dotfiles"
version = "0.1.0"

[dependencies]
clap = "2.29.4"
failure = "0.1.1"
git2 = "0.6.11"
lazy_static = "1.0.0"
slog = "2.0.12"
slog-async = "2.1.0"
slog-scope = "4.0.1"
slog-term = "2.2.0"
